[package]
name = "cheese"
version = "0.0.1"
edition = "2024"
rust-version = "1.85"
license = "MIT"
authors = ["Weavers Engineering"]
repository = "https://github.com/Weavers-Engineering/cheese"
description = "say cheese: pixel-perfect screenshots of your terminal"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
